apiVersion: apps/v1
kind: apiVersion: v1
kind: Service
metadata:
  name: vpromq
spec:
  selector:
    app: vpromq01
  ports:
  - port: 15672
    targetPort: vpromq01-port
    protocol: TCP
  type: ClusterIP
